version: "3.8"

services:
  web:
    image: nginx:alpine
    volumes:
      - /home/jose/apps/caro-fisioterapia/public:/usr/share/nginx/html
      - /home/jose/apps/caro-fisioterapia/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dokploy-network
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        # Enrutador HTTP (Redirección automática a HTTPS)
        - "traefik.http.routers.caro-fisioterapia-http.entrypoints=web"
        - "traefik.http.routers.caro-fisioterapia-http.middlewares=redirect-to-https@docker"
        - "traefik.http.routers.caro-fisioterapia-http.rule=Host(`caro.prosuite.pro`)"
        # Enrutador HTTPS
        - "traefik.http.routers.caro-fisioterapia.entrypoints=websecure"
        - "traefik.http.routers.caro-fisioterapia.rule=Host(`caro.prosuite.pro`)"
        - "traefik.http.routers.caro-fisioterapia.tls.certresolver=letsencrypt"
        # Puerto interno del contenedor Nginx
        - "traefik.http.services.caro-fisioterapia.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
